theme: jekyll-theme-cayman
title: Vermont Go Championship
description: Fall Tournament (Online)
author: Jack Cary
header_pages:
github:
  is_project_page: false
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
